### ISSUE TITLE
Could you provide an example?

### ISSUE THREAD

**Issue by FTD-ZF** [MisterAlex95/react-native-record-sound#3]
I don't know how to use it.

**Comment by MisterAlex95** [comment]
https://github.com/MisterAlex95/react-native-record-sound#how-to-use

there are only two functions: startRecord(<path.mp4>); and stopRecord(); .. extremely simple

EDIT: 
Oh you want a complete working example?

**Comment by FTD-ZF** [comment]
I'm a newcomer. And try to use your only two functions, and I am not familiar  with React-Native, so it's error. Could you show  a simple  working example ?   I want to learn how to use react-native-record.

**Comment by FTD-ZF** [comment]
Error:   ReactNativeRecordSound.startRecord got 1 arguments, expected 2

**Comment by MisterAlex95** [comment]
Oh yes excuse me my example doesn't work.
try it: 

> startRecord(path.mp4, (err) => {console.log(err);});

https://github.com/MisterAlex95/react-native-record-sound/commit/f5ca809c23fc4d07450ac587019678453e5bf4d0

**Comment by MisterAlex95** [comment]
It's ok ?

**Comment by FTD-ZF** [comment]
year,It's ok.  Thank  you!  You're a good developer.

**Comment by wowaji** [comment]
@helloworld-rn 

How do you solve this?

Error: ReactNativeRecordSound.startRecord got 1 arguments, expected 2

**Comment by MisterAlex95** [comment]
The second argument is à callback : fonction(err)
