### ISSUE TITLE
Help: what is path in your example?

### ISSUE THREAD

**Issue by juanpasolano** [MisterAlex95/react-native-record-sound#4]
I'm trying to implement your plugin but I don't know what is the `path` variable in your `Record.startRecord(path + '/sound.mp4', function(a))`. Without it I get `RecordModulejava.io.FileNotFoundException: /sound.mp4: open failed: EROFS (Read-only file system)`. I don't see a File System Api in React Native core, are you using a 3rd party plugin?

I've added RECORD_AUDIO, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE permissions

Thank you sir!

**Comment by MisterAlex95** [comment]
Yes I use RNFS ! 
const RNFS = require('react-native-fs');
const pathPrefix = RNFS.DocumentDirectoryPath;

so you can use it like this: 

> Record.startRecord(pathPrefix + '/sound.mp4', function(a)).
