### ISSUE TITLE
Help,I got the error "setAudioSource failed"

### ISSUE THREAD

**Issue by wowaji** [MisterAlex95/react-native-record-sound#6]
error :"setAudioSource failed"

Did I make any mistake?

Record.startRecord('../rec'+ 'sound.mp4',(err)=>{console.log(err)});

**Comment by 277850318** [comment]
the file path is error

**Comment by wowaji** [comment]
What is the right path?

**Comment by 277850318** [comment]
var RNFS = require('react-native-fs');
// create a path you want to write to
var path = RNFS.DocumentDirectoryPath + '/test.mp3';

我是用这个组件去获取目录的 但是这个组件不完全对 
他生成的地址是/data/com.myproject/files/
正确的应该是/storage/emulated/0/Android/data/com.myproject/files/

**Comment by wowaji** [comment]
谢谢~作者没写明白路径用法我以为可以直接保存

**Comment by 277850318** [comment]
我开始也以为是这样的。。。你顺便帮我测下我反馈的那个问题   录制的声音不是很清晰  跟微信或系统的那个录音机音质的对比

**Comment by wowaji** [comment]
我还测试不了，一安装react-native-fs改build.gradle就报错，‘Image'has no propType for native prop 'RCTImageView.overlayColor。。。

可能与我的RN版本有关，0.19

------------------ 原始邮件 ------------------
发件人: "zhoujian";notifications@github.com;
发送时间: 2016年7月31日(星期天) 晚上6:20
收件人: "MisterAlex95/react-native-record-sound"react-native-record-sound@noreply.github.com; 
抄送: "Ji"1397752@qq.com; "Author"author@noreply.github.com; 
主题: Re: [MisterAlex95/react-native-record-sound] Help,I got the error"setAudioSource failed" (#6)

我开始也以为是这样的。。。你顺便帮我测下我反馈的那个问题   录制的声音不是很清晰  跟微信或系统的那个录音机音质的对比

**Comment by MisterAlex95** [comment]
Thanks 277850318.
I use RNFS too.

**Comment by MisterAlex95** [comment]
May i close this issue ?

**Comment by wowaji** [comment]
of course~
