### ISSUE TITLE
Exception AVAudioSession recordPermission 

### ISSUE THREAD

**Issue by 277850318** [MisterAlex95/react-native-record-sound#8]
can you  support record in ios7.1?

**Comment by MisterAlex95** [comment]
It does not work already?

**Comment by 277850318** [comment]
in ios7.1 it does not work,hope to fix

**Comment by MisterAlex95** [comment]
I'm sorry I have no more mac. I can't update the module.

If someone can do it and propose a pull request it will be cool !
